version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "82:82"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist:/etc/nginx/html
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
